version: '2.4'

services:
  db:
    image: postgres:12.1
    container_name: db
    volumes:
      - ./db-data:/var/lib/postgresql/data
  web:
    build: .
    container_name: django
    restart: always
    command: ["sh","-c", "sleep 20 && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
